apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: health-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: health-system
  app.kubernetes.io/managed-by: kustomize

images:
  - name: health-system
    newName: health-system
    newTag: latest
