apiVersion: v1
kind: ConfigMap
metadata:
  name: health-system-config
data:
  SPRING_PROFILES_ACTIVE: "kubernetes,staging"
  SPRING_JPA_SHOW_SQL: "false"
  LOGGING_LEVEL_COM_DEVDISHON: "INFO"
  SPRINGDOC_SWAGGER_UI_ENABLED: "true"
