apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: health-system

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: health-system
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/health-system/staging
    newTag: ${IMAGE_TAG}
